In [36]:
import numpy as np
import pandas as pd
from math import ceil
from sklearn.model_selection import train_test_split

In [3]:
iris = pd.read_csv('dados/iris.csv')
iris.head()

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Amostra Simple

In [4]:
# Criando um array[] de 0 e 1, de tamanho de 150 alementos.
amostra_simples = np.random.choice(a=[0, 1], size=150, replace=True, p=[0.2, 0.8])
amostra_simples

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [6]:
# Numero de 0 contido no array
len(amostra_simples[amostra_simples == 0])

37

In [8]:
# Gerando uma amostra simples do conjunto de dados iris.csv
iris_simples = iris.loc[amostra_simples == 0]
iris_simples.head()

sepal length  sepal width  petal length  petal width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa

In [9]:
# Tamnho da amostra
len(iris_simples)

37

Amostra Sistematica

In [32]:
# Tamanho do intervalo da amostra
i = ceil(150 / 10)

# Valor randomico para iniciar a amostra contido no intervalo [0, 15)
valor_inicial = np.random.randint(low=0, high=i, size=1)
valor_inicial

array([13])

In [33]:
# Array de 10 elementos, com valor iniciai igua a 'valor_inicial' 
amostra_sistematica = np.arange(valor_inicial, len(iris), i)
amostra_sistematica

array([ 13,  28,  43,  58,  73,  88, 103, 118, 133, 148])

In [35]:
# Gerando uma amostra sistematica do conjunto de dados iris.csv
iris_sistematica = iris.loc[amostra_sistematica]
iris_sistematica

sepal length  sepal width  petal length  petal width            class
13            4.3          3.0           1.1          0.1      Iris-setosa
28            5.2          3.4           1.4          0.2      Iris-setosa
43            5.0          3.5           1.6          0.6      Iris-setosa
58            6.6          2.9           4.6          1.3  Iris-versicolor
73            6.1          2.8           4.7          1.2  Iris-versicolor
88            5.6          3.0           4.1          1.3  Iris-versicolor
103           6.3          2.9           5.6          1.8   Iris-virginica
118           7.7          2.6           6.9          2.3   Iris-virginica
133           6.3          2.8           5.1          1.5   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica

Amostra Estratificada

In [37]:
# Contagem da coluna 'class'
iris['class'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: class, dtype: int64

In [45]:
X, _, Y, _ = train_test_split(iris.iloc[:, 0:4], iris.iloc[:, 4], test_size=0.8, stratify=iris.iloc[:, 4])
Y.value_counts()

Iris-setosa        10
Iris-virginica     10
Iris-versicolor    10
Name: class, dtype: int64